name: Package verification
on:
   push:
      branches-ignore:
      - develop
      - release/**
   workflow_dispatch: null
env:
   GITHUB_TOKEN: ${{github.token}}
   MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
   MAVEN_DEFAULT_ARGS: --batch-mode --update-snapshots
   MAVEN_ADDITIONAL_ARGS_FOR_BUILDING_PACKAGE: -Dbuilding
jobs:
   verify-package:
      if: github.event_name == 'workflow_dispatch' || !contains(github.event.head_commit.message, 'skip ci')
      runs-on: ubuntu-latest
      steps:
      -  uses: actions/checkout@v2
      -  uses: actions/setup-java@v1
         with:
            java-version: 11
      -  uses: actions/cache@v2
         with:
            path: ~/.m2/repository
            key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
            restore-keys: ${{runner.os}}-maven-
      -  run: .github/workflows/scripts/verify-package.sh